name: Push-to-EC2
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@v2
      with:
        REMOTE_HOST: "54.232.231.212"
        REMOTE_USER: "ubuntu"
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        TARGET: "/home/projects/Elections.API"

    - name: SSH into EC2 and execute commands
      uses: appleboy/ssh-action@master
      with:
        host: 54.232.231.212
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/projects/Elections.API
          docker build -t elections-api:latest .
          docker stop elections-api || true
          docker rm elections-api || true
          docker run -d -p 5000:80 --name elections-api elections-api:latest
